name: SFDX Scanner

on:
  pull_request:

jobs:
  scanner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Run SFDX Scanner
        run: sf scanner run --target force-app
